matrix:
  include:
    - os: linux
      language: cpp
      dist: xenial
      name: Linux-g++
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
      install:
        - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 100 --slave /usr/bin/g++ g++ /usr/bin/g++-9
      script:
        - printf "about\nq" | python3 launch.py --f build run
    - os: linux
      language: cpp
      dist: xenial
      name: Linux-clang
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
      install:
        - export CC="clang"
        - export CXX="clang++"
      script:
        - printf "about\nq" | python3 launch.py --f build run
    - os: windows
      language: cpp
      name: Windows-VS
      env:
        - MSBUILD_PATH="C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin"
      install:
        - export PATH=$MSBUILD_PATH:$PATH
      script:
        - (echo about & echo.q) | python launch.py --f build run
    - os: osx
      language: cpp
      osx_image: xcode10.2
      name: macOS-g++
      install:
        - export CC="gcc-8"
        - export CXX="g++-8"
      script:
        - printf "about\nq" | python3 launch.py --f build run
    - os: osx
      language: cpp
      osx_image: xcode10.2
      name: macOS-clang
      addons:
        homebrew:
          packages:
            - llvm
      install:
        - export CC="/usr/local/opt/llvm/bin/clang"
        - export CXX="/usr/local/opt/llvm/bin/clang++"
        - export LDFLAGS="-L/usr/local/opt/llvm/lib"
        - export CPPFLAGS="-I/usr/local/opt/llvm/include"
      script:
        - printf "about\nq" | python3 launch.py --f build run
    - os: linux
      language: python
      dist: xenial
      python:
        - "3.7"
      name: Parser script
      install:
        - pip3 install bs4 requests termcolor
      script:
        - python3 scripts/parser.py test
