matrix:
  include:
    - os: linux
      language: cpp
      dist: bionic
      name: Linux-g++
      compiler: gcc
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages:
            - g++-9
      install:
        - >
          sudo update-alternatives
          --install /usr/bin/gcc gcc /usr/bin/gcc-9 100
          --slave /usr/bin/g++ g++ /usr/bin/g++-9
      script:
        - printf "about\nq" | python3 launch.py --f build run
    - os: linux
      language: cpp
      dist: bionic
      name: Linux-clang
      compiler: clang
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages:
            - g++-9
      install:
        - export CC="clang"
        - export CXX="clang++"
      script:
        - printf "about\nq" | python3 launch.py --f build run
    - os: windows
      language: cpp
      name: Windows-VS
      env:
        - MSBUILD_PATH="C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin"
      install:
        - export PATH=$MSBUILD_PATH:$PATH
      script:
        - echo about > launch.txt
        - echo q >> launch.txt
        - python launch.py --f build run < launch.txt
