environments:
  - name: e1
    tasks:
      - name: t1
        language: cpp
      - name: t2
        language: c
  - name: e2
    tasks:
      - name: t1
        language: cpp

global:
  compilers:
    cpp: g++ @name@.cpp -o @name@
    c: gcc @name@.c -o @name@
