global:
  python_interpreter: python3
  editor: vim "@name@.@lang@"
  autosave: on
  compilers:
    c: gcc "@name@.c" -o "@name@"
    cpp: g++ "@name@.cpp" -o "@name@"
  runners:
    py: python "@name@.py"
