global:
  python_interpreter: python
  autosave: on
  editor: notepad "@name@.@lang@" &
  compilers:
    c: gcc @name@.c -o @name@
    cpp: g++ @name@.cpp -o @name@
  runners:
    py: python @name@.py
