name: Build and run

on: [push, pull_request]

jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup environment
      run: |
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test
        sudo apt update
        sudo apt install g++-9
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 100 --slave /usr/bin/g++ g++ /usr/bin/g++-9
    - name: Build application
      run: |
        printf "about\nq" | python3 launch.py --f build run
  windows-build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build application
      run: |
        echo about > launch.txt
        echo q >> launch.txt
        cmd /c 'python launch.py --f build run < launch.txt'
  macos-gcc-build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup environment
      run: |
        brew install gcc
    - name: Build application
      run: |
        printf "about\nq" | python3 launch.py --f build run --b CMAKE_C_COMPILER=gcc-9 CMAKE_CXX_COMPILER=g++-9 EXP_FS=1
  macos-appleclang-build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build application
      run: |
        printf "about\nq" | python3 launch.py --f build run
