name: Scripts

on: [push, pull_request]

jobs:
  python-linter:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.8'
        architecture: 'x64'
    - name: Install dependencies
      run: |
        python -m pip install flake8
    - name: Run linter
      run: >-
          python -m flake8
          --max-line-length 120
          launch.py
          scripts/parser.py
          scripts/test_parser.py
  parser-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.8'
        architecture: 'x64'
    - name: Install dependencies
      run: |
        python -m pip install bs4
    - name: Run linter
      run: |
        python scripts/parser.py test
